#!/usr/bin/env python3
"""
Figure 2 — 克隆命运锁定预测响应（核心主图）
  Panel A: 命运锁定概念示意图（NK-Locked vs Tex-Differentiated）
  Panel B: 森林图（NK-Locked 正向 vs Tex 负向，颜色区分方向）
  Panel C: 响应组间 Ratio 比较箱线图
  Panel D: 频数分布直方图
"""
import os, sys
import numpy as np, pandas as pd, scipy.stats as ss
import scanpy as sc
import statsmodels.formula.api as smf
from sklearn.metrics import roc_auc_score
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import warnings
warnings.filterwarnings('ignore')

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

DATA = os.path.dirname(HERE)
ADATA = os.path.join(DATA, 'adata')
RESULT = os.path.join(DATA, 'result')
os.makedirs(RESULT, exist_ok=True)

print('=== Loading per_patient_metrics.csv ===', flush=True)
print('SOURCE: per_patient_metrics.csv is generated by figure1.py from GSE243013_T_cells.h5ad', flush=True)
print('FILTER: Only patients with pCR or non-MPR response are included (MPR excluded for binary OR)', flush=True)
pdf = pd.read_csv(os.path.join(RESULT, 'per_patient_metrics.csv'))
pdf = pdf.dropna(subset=['nk_dominant_ratio'])
# 发表版OR：仅pCR vs non-MPR二分类（MPR患者不参与OR计算）
pdf = pdf[pdf['response'].isin(['pCR', 'non-MPR'])]
print(f'n_patients = {len(pdf)}  pCR={(pdf.response=="pCR").sum()}  non-MPR={(pdf.response=="non-MPR").sum()}', flush=True)
print('NOTE: This definition (188 patients) is the authoritative version for publication.', flush=True)
print('      T05_analysis.py uses 228 patients (includes MPR), which explains OR differences.', flush=True)

# ============= 计算 NK-Locked 和 Tex 的 OR =============
# NK-Locked: nk_dominant_ratio 越高 → pCR（正向，OR>1）
m_nk = smf.logit('resp_bin ~ nk_dominant_ratio', data=pdf).fit(disp=0)
or_nk = float(np.exp(m_nk.params['nk_dominant_ratio']))
ci_nk = np.exp(m_nk.conf_int().loc['nk_dominant_ratio'])
p_nk = float(m_nk.pvalues['nk_dominant_ratio'])

# Tex signature: nk_pct 越低（即Tex比例越高）→ non-MPR（负向，OR<1）
# 直接用 nk_pct 预测 pCR，OR 应该 < 1（NK越少，pCR概率越低）
m_tex = smf.logit('resp_bin ~ nk_pct', data=pdf).fit(disp=0)
or_tex = float(np.exp(m_tex.params['nk_pct']))
ci_tex = np.exp(m_tex.conf_int().loc['nk_pct'])
p_tex = float(m_tex.pvalues['nk_pct'])

# 多变量
m_multi = smf.logit('resp_bin ~ nk_dominant_ratio + total_clone_count + cd8t', data=pdf).fit(disp=0)
or_multi = float(np.exp(m_multi.params['nk_dominant_ratio']))
ci_multi = np.exp(m_multi.conf_int().loc['nk_dominant_ratio'])
p_multi = float(m_multi.pvalues['nk_dominant_ratio'])

print(f'NK-Locked OR = {or_nk:.2f}  [{ci_nk[0]:.2f}, {ci_nk[1]:.2f}]  p = {p_nk:.3e}', flush=True)
print(f'Tex (NK_pct) OR = {or_tex:.2f}  [{ci_tex[0]:.2f}, {ci_tex[1]:.2f}]  p = {p_tex:.3e}', flush=True)
print(f'Adjusted OR = {or_multi:.2f}  [{ci_multi[0]:.2f}, {ci_multi[1]:.2f}]  p = {p_multi:.3e}', flush=True)

# ============= Panel D: 频数分布直方图数据 =============
zero_frac = (pdf['nk_dominant_ratio'] == 0).mean() * 100
print(f'NK-Locked Ratio = 0 的患者比例: {zero_frac:.1f}%', flush=True)

g0 = pdf[pdf.response=='non-MPR']['nk_dominant_ratio']
g1 = pdf[pdf.response=='pCR']['nk_dominant_ratio']
mw = ss.mannwhitneyu(g1, g0, alternative='two-sided')

# ============= 组合绘图 =============
print('=== Composing Figure 2 ===', flush=True)
fig = plt.figure(figsize=(16, 12))
gs = fig.add_gridspec(3, 2, hspace=0.4, wspace=0.3, height_ratios=[0.9, 1, 0.8])

# ---- Panel A: 示意图 ----
ax1 = fig.add_subplot(gs[0, :])
ax1.set_xlim(0, 10)
ax1.set_ylim(0, 5)
ax1.axis('off')

ax1.text(5, 4.7, 'Clonal Fate Locking Model', fontsize=15, fontweight='bold', ha='center')

# NK-Locked 框
box_nk = FancyBboxPatch((0.3, 0.8), 4.2, 3.2, boxstyle="round,pad=0.1",
                        facecolor='#FADBD8', edgecolor='#E74C3C', linewidth=2, alpha=0.8)
ax1.add_patch(box_nk)
ax1.text(2.4, 3.6, 'NK-Locked', fontsize=14, fontweight='bold', ha='center', color='#C0392B')
ax1.text(2.4, 3.0, 'Stemness maintained', fontsize=10, ha='center', color='#922B21')
ax1.text(2.4, 2.5, 'KLF2+ FGFBP2+', fontsize=10, ha='center', color='#922B21')
ax1.text(2.4, 2.0, 'Clonally expanded', fontsize=10, ha='center', color='#922B21')
ax1.text(2.4, 1.4, '→ pCR (Good response)', fontsize=10, fontweight='bold', ha='center', color='#27AE60')

# Tex-Differentiated 框
box_tex = FancyBboxPatch((5.5, 0.8), 4.2, 3.2, boxstyle="round,pad=0.1",
                         facecolor='#D6EAF8', edgecolor='#2E86C1', linewidth=2, alpha=0.8)
ax1.add_patch(box_tex)
ax1.text(7.6, 3.6, 'Tex-Differentiated', fontsize=14, fontweight='bold', ha='center', color='#1A5276')
ax1.text(7.6, 3.0, 'Terminal exhaustion', fontsize=10, ha='center', color='#1A5276')
ax1.text(7.6, 2.5, 'TOX+ PD-1+', fontsize=10, ha='center', color='#1A5276')
ax1.text(7.6, 2.0, 'Diversified clones', fontsize=10, ha='center', color='#1A5276')
ax1.text(7.6, 1.4, '→ non-MPR (Poor response)', fontsize=10, fontweight='bold', ha='center', color='#C0392B')

# 分化箭头
arrow = FancyArrowPatch((4.7, 2.4), (5.3, 2.4),
                        arrowstyle='->', mutation_scale=20, linewidth=2, color='gray')
ax1.add_patch(arrow)
ax1.text(5, 2.7, 'Differentiation', fontsize=9, ha='center', color='gray', style='italic')

ax1.text(-0.03, 1.02, 'A', transform=ax1.transAxes, fontsize=20, fontweight='bold')

# ---- Panel B: 森林图（颜色区分方向）----
ax2 = fig.add_subplot(gs[1, 0])

forest_items = [
    {'label': 'NK-Locked ratio\n(Univariable)', 'or': or_nk, 'lo': ci_nk[0], 'hi': ci_nk[1], 'color': '#27AE60', 'direction': 'positive'},
    {'label': 'NK-Locked ratio\n(Multivariable)', 'or': or_multi, 'lo': ci_multi[0], 'hi': ci_multi[1], 'color': '#1E8449', 'direction': 'positive'},
    {'label': 'NK-like proportion\n(Univariable)', 'or': or_tex, 'lo': ci_tex[0], 'hi': ci_tex[1], 'color': '#E74C3C', 'direction': 'positive'},
]

y_positions = [2, 1, 0]

for y, item in zip(y_positions, forest_items):
    ax2.plot([item['lo'], item['hi']], [y, y], color=item['color'], lw=2.5, solid_capstyle='round')
    ax2.plot([item['or'], item['or']], [y-0.18, y+0.18], color=item['color'], lw=5, solid_capstyle='round', marker='D', markersize=8)
    if item['or'] > 1:
        ax2.text(item['hi'] * 1.15, y, f"OR = {item['or']:.2f}\n[{item['lo']:.2f}, {item['hi']:.2f}]",
                 va='center', fontsize=9, color=item['color'], fontweight='bold')
    else:
        ax2.text(item['lo'] * 0.5, y, f"OR = {item['or']:.2f}\n[{item['lo']:.2f}, {item['hi']:.2f}]",
                 va='center', fontsize=9, color=item['color'], fontweight='bold', ha='right')

ax2.axvline(1, color='black', ls='-', lw=1.5, alpha=0.6)
ax2.axvspan(0.01, 1, alpha=0.08, color='#E74C3C')
ax2.axvspan(1, 200, alpha=0.08, color='#27AE60')
ax2.text(0.3, 2.6, 'Protective\n(non-MPR)', fontsize=9, color='#C0392B', ha='center', fontweight='bold')
ax2.text(10, 2.6, 'Risk\n(pCR)', fontsize=9, color='#1E8449', ha='center', fontweight='bold')

ax2.set_yticks(y_positions)
ax2.set_yticklabels([item['label'] for item in forest_items], fontsize=9)
ax2.set_xlabel('Odds Ratio for pCR (log scale)', fontsize=11)
ax2.set_xscale('log')

all_hi = max(item['hi'] for item in forest_items)
all_lo = min(item['lo'] for item in forest_items)
xmin = 0.05
xmax = all_hi * 3
ax2.set_xlim(xmin, xmax)

ax2.set_title('Forest Plot: Clonal Fate vs Response', fontsize=13, fontweight='bold')
ax2.grid(axis='x', alpha=0.3, ls=':')
ax2.text(-0.15, 1.05, 'B', transform=ax2.transAxes, fontsize=20, fontweight='bold')

# ---- Panel C: 箱线图 ----
ax3 = fig.add_subplot(gs[1, 1])

box_data = [g0.values, g1.values]
bp = ax3.boxplot(box_data, patch_artist=True, showfliers=False, widths=0.55)

colors = ['#5DADE2', '#E74C3C']
for patch, c in zip(bp['boxes'], colors):
    patch.set_facecolor(c)
    patch.set_alpha(0.75)
for med in bp['medians']:
    med.set_color('black')
    med.set_linewidth(2)
for whisker in bp['whiskers']:
    whisker.set_color('gray')
    whisker.set_linewidth(1.2)
for cap in bp['caps']:
    cap.set_color('gray')

np.random.seed(42)
x_jitter_0 = np.random.normal(1, 0.06, len(g0))
x_jitter_1 = np.random.normal(2, 0.06, len(g1))
ax3.scatter(x_jitter_0, g0, s=40, c='#2874A6', alpha=0.7, edgecolor='white', linewidth=0.8, zorder=3)
ax3.scatter(x_jitter_1, g1, s=40, c='#C0392B', alpha=0.7, edgecolor='white', linewidth=0.8, zorder=3)

ax3.set_xticks([1, 2])
ax3.set_xticklabels(['non-MPR\n(Poor)', 'pCR\n(Good)'], fontsize=11, fontweight='bold')
ax3.set_ylabel('NK-Locked ratio', fontsize=11)
ax3.set_title('NK-Locked Ratio by Response', fontsize=13, fontweight='bold')

p_text = f'Mann-Whitney p = {mw.pvalue:.2e}'
ax3.text(0.5, 0.95, p_text, transform=ax3.transAxes, ha='center', va='top',
         fontsize=10, fontweight='bold', color='#C0392B',
         bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='lightgray', alpha=0.9))

ax3.text(-0.15, 1.05, 'C', transform=ax3.transAxes, fontsize=20, fontweight='bold')

# ---- Panel D: 频数分布直方图 ----
ax4 = fig.add_subplot(gs[2, :])

bins = np.linspace(0, 0.25, 25)

ax4.hist([g0.values, g1.values], bins=bins,
         color=['#5DADE2', '#E74C3C'], alpha=0.7, label=[f'non-MPR (n={len(g0)})', f'pCR (n={len(g1)})'],
         edgecolor='white', linewidth=0.5, density=False)

ax4.axvline(g0.median(), color='#2874A6', ls='--', lw=2, alpha=0.8)
ax4.axvline(g1.median(), color='#C0392B', ls='--', lw=2, alpha=0.8)
ax4.text(g0.median() + 0.003, ax4.get_ylim()[1] * 0.85, f'non-MPR\nmedian={g0.median():.3f}',
         color='#2874A6', fontsize=9, fontweight='bold')
ax4.text(g1.median() + 0.003, ax4.get_ylim()[1] * 0.65, f'pCR\nmedian={g1.median():.3f}',
         color='#C0392B', fontsize=9, fontweight='bold')

# 标注零值比例
n_zero_all = (pdf['nk_dominant_ratio'] == 0).sum()
ax4.text(0.01, ax4.get_ylim()[1] * 0.95, f'{zero_frac:.1f}% patients = 0',
         fontsize=11, fontweight='bold', color='#7F8C8D',
         bbox=dict(boxstyle='round,pad=0.3', facecolor='#F2F3F4', edgecolor='lightgray'))

ax4.set_xlabel('NK-Locked ratio', fontsize=11)
ax4.set_ylabel('Number of patients', fontsize=11)
ax4.set_title('Distribution of NK-Locked Ratio', fontsize=13, fontweight='bold')
ax4.legend(frameon=False, fontsize=10)
ax4.grid(axis='y', alpha=0.3, ls=':')

ax4.text(-0.02, 1.05, 'D', transform=ax4.transAxes, fontsize=20, fontweight='bold')

plt.tight_layout()
plt.savefig(os.path.join(RESULT, 'Fig2_clonal_fate.png'), dpi=300)
plt.savefig(os.path.join(RESULT, 'Fig2_clonal_fate.pdf'))
plt.close()
print('Fig2 saved to result/Fig2_clonal_fate.png', flush=True)

# ============= 保存统计 =============
stats = dict(
    nk_locked_or = or_nk,
    nk_locked_or_lo = ci_nk[0],
    nk_locked_or_hi = ci_nk[1],
    nk_locked_p = p_nk,
    tex_or = or_tex,
    tex_or_lo = ci_tex[0],
    tex_or_hi = ci_tex[1],
    tex_p = p_tex,
    adj_or = or_multi,
    adj_or_lo = ci_multi[0],
    adj_or_hi = ci_multi[1],
    adj_p = p_multi,
    mwu_p = mw.pvalue,
    median_nklock_nonMPR = float(g0.median()),
    median_nklock_pCR = float(g1.median()),
    zero_fraction_pct = float(zero_frac),
    n_zero_patients = int(n_zero_all),
)
pd.Series(stats).to_csv(os.path.join(RESULT, 'fig2_stats.csv'))

# ============= Bootstrap 内部验证 (1000 resamples) =============
print('=== Bootstrap internal validation (1000 resamples) ===', flush=True)

print('Loading GSE243013_T_cells.h5ad for threshold analysis ...', flush=True)
adata_boot = sc.read_h5ad(os.path.join(ADATA, 'GSE243013_T_cells.h5ad'))
for c in ['sub_cell_type', 'sampleID', 'pathological_response',
          'clonotype', 'clonotype_number', 'major_cell_type', 'cancer_type']:
    adata_boot.obs[c] = adata_boot.obs[c].astype(str)

adata_boot.obs['is_cd8'] = adata_boot.obs['sub_cell_type'].str.startswith('CD8T')
adata_boot.obs['is_nklike'] = adata_boot.obs['sub_cell_type'] == 'CD8T_NK-like_FGFBP2'


def compute_per_patient_threshold(ad, clone_count_thr: int, nk_frac_thr: float = 0.5):
    rows = []
    for pid, sub in ad.obs.groupby('sampleID'):
        resp = sub['pathological_response'].iloc[0]
        if resp not in ('pCR', 'non-MPR'):
            continue
        cdm = sub['is_cd8']
        cd8n = int(cdm.sum())
        if cd8n == 0:
            continue
        cd8p = sub[cdm]
        cc = cd8p['clonotype'].value_counts()
        big = cc[cc >= clone_count_thr]
        fracs = []
        for cl in big.index:
            clc = cd8p[cd8p['clonotype'] == cl]
            nk_in_cl = float(clc['is_nklike'].sum())
            fracs.append(nk_in_cl / len(clc))
        nk_dom = float(np.mean(fracs)) if fracs else np.nan
        nk_locked = int(nk_dom > nk_frac_thr) if not np.isnan(nk_dom) else 0
        ct = int(cc.shape[0])
        ct_val = str(sub['cancer_type'].iloc[0]) if 'cancer_type' in sub.columns else 'LUAD'
        rows.append(dict(
            patient=str(pid), response=resp, resp_bin=int(resp == 'pCR'),
            cd8t=cd8n, total_clone_count=ct,
            nk_dominant_ratio=nk_dom, nk_locked=nk_locked,
            is_LUAD=int(ct_val == 'LUAD'),
        ))
    return pd.DataFrame(rows)


base_thr = compute_per_patient_threshold(adata_boot, clone_count_thr=5, nk_frac_thr=0.5)
print(f'Bootstrap base: n={len(base_thr)}  pCR={int(base_thr.resp_bin.sum())}  non-MPR={int((1-base_thr.resp_bin).sum())}', flush=True)

m_real = smf.logit(
    'resp_bin ~ nk_locked + total_clone_count + cd8t + is_LUAD',
    data=base_thr
).fit(disp=0)
auc_real = roc_auc_score(base_thr['resp_bin'], m_real.predict(base_thr))
or_real = float(np.exp(m_real.params['nk_locked']))
ci_real = np.exp(m_real.conf_int().loc['nk_locked'])
p_real = float(m_real.pvalues['nk_locked'])
print(f'Real Model C: OR={or_real:.3f} [{ci_real[0]:.3f},{ci_real[1]:.3f}]  p={p_real:.3e}  AUC={auc_real:.3f}', flush=True)

N_BOOT = 1000
rng = np.random.RandomState(42)
boot_or = np.zeros(N_BOOT)
boot_auc = np.zeros(N_BOOT)
n_success = 0
for i in range(N_BOOT):
    idx = rng.randint(0, len(base_thr), size=len(base_thr))
    bdf = base_thr.iloc[idx].reset_index(drop=True)
    if bdf['resp_bin'].nunique() < 2:
        continue
    try:
        m_b = smf.logit(
            'resp_bin ~ nk_locked + total_clone_count + cd8t + is_LUAD',
            data=bdf
        ).fit(disp=0, maxiter=100)
        if np.isnan(m_b.params['nk_locked']):
            continue
        boot_or[i] = np.exp(m_b.params['nk_locked'])
        if bdf['resp_bin'].nunique() == 2:
            boot_auc[i] = roc_auc_score(bdf['resp_bin'], m_b.predict(bdf))
        n_success += 1
    except Exception:
        continue

boot_or = boot_or[boot_or != 0]
boot_auc = boot_auc[boot_auc != 0]
or_med = float(np.median(boot_or[boot_or < 1e6]))
or_lo = float(np.percentile(boot_or[boot_or < 1e6], 2.5))
or_hi = float(np.percentile(boot_or[boot_or < 1e6], 97.5))
auc_mean = float(np.mean(boot_auc))
auc_med = float(np.median(boot_auc))
auc_lo = float(np.percentile(boot_auc, 2.5))
auc_hi = float(np.percentile(boot_auc, 97.5))
auc_bc = 2 * auc_real - auc_mean
print(f'Bootstrap: n_success={n_success}/{N_BOOT}', flush=True)
print(f'  OR median={or_med:.3f}  95%CI [{or_lo:.3f}, {or_hi:.3f}]', flush=True)
print(f'  AUC mean={auc_mean:.3f}, median={auc_med:.3f}  95%CI [{auc_lo:.3f}, {auc_hi:.3f}]  bias-corrected={auc_bc:.3f}', flush=True)

boot_csv = os.path.join(RESULT, 'fig2_bootstrap_auc.csv')
pd.DataFrame([dict(
    metric='Model_C_nk_locked',
    n_patients=len(base_thr),
    n_bootstrap=N_BOOT,
    n_success=int(n_success),
    or_real=or_real, or_lo_real=float(ci_real[0]), or_hi_real=float(ci_real[1]),
    p_real=p_real, auc_real=auc_real,
    or_boot_median=or_med, or_boot_lo=or_lo, or_boot_hi=or_hi,
    auc_boot_mean=auc_mean, auc_boot_median=auc_med,
    auc_boot_lo=auc_lo, auc_boot_hi=auc_hi, auc_bc=auc_bc,
)]).to_csv(boot_csv, index=False)
print(f'Saved -> {boot_csv}', flush=True)

# ============= 阈值敏感性分析 =============
print('=== Threshold sensitivity analysis ===', flush=True)
clone_thrs = [3, 5, 10, 15, 20, 30, 50]
nk_frac_thrs = [0.3, 0.4, 0.5, 0.6, 0.7]
sens_rows = []
for ct_thr in clone_thrs:
    for nk_thr in nk_frac_thrs:
        df = compute_per_patient_threshold(adata_boot, clone_count_thr=ct_thr, nk_frac_thr=nk_thr)
        n_pat = len(df)
        if df['resp_bin'].nunique() < 2 or df['nk_locked'].nunique() < 2:
            sens_rows.append(dict(
                clone_threshold=ct_thr, nk_frac_threshold=nk_thr,
                n_patients=n_pat, n_locked=int(df['nk_locked'].sum()),
                or_value=np.nan, or_lo=np.nan, or_hi=np.nan, p_value=np.nan,
                note='Insufficient variation',
            ))
            continue
        try:
            m = smf.logit(
                'resp_bin ~ nk_locked + total_clone_count + cd8t + is_LUAD',
                data=df
            ).fit(disp=0, maxiter=100)
            or_v = float(np.exp(m.params['nk_locked']))
            ci = np.exp(m.conf_int().loc['nk_locked'])
            p_v = float(m.pvalues['nk_locked'])
            sens_rows.append(dict(
                clone_threshold=ct_thr, nk_frac_threshold=nk_thr,
                n_patients=n_pat, n_locked=int(df['nk_locked'].sum()),
                or_value=or_v, or_lo=float(ci[0]), or_hi=float(ci[1]), p_value=p_v,
                note='OK',
            ))
        except Exception as e:
            sens_rows.append(dict(
                clone_threshold=ct_thr, nk_frac_threshold=nk_thr,
                n_patients=n_pat, n_locked=int(df['nk_locked'].sum()),
                or_value=np.nan, or_lo=np.nan, or_hi=np.nan, p_value=np.nan,
                note=f'Fit failed: {e}',
            ))
        last = sens_rows[-1]
        print(f'  clone={ct_thr}, nk_frac={nk_thr}: OR={last["or_value"]:.2f}, p={last["p_value"]:.3e}', flush=True)

sens_df = pd.DataFrame(sens_rows)
sens_csv = os.path.join(RESULT, 'fig2_threshold_sensitivity.csv')
sens_df.to_csv(sens_csv, index=False)
print(f'Saved -> {sens_csv}', flush=True)

# 阈值曲线图
fig, axes = plt.subplots(1, 5, figsize=(22, 4.5), sharey=True)
colors = ['#E74C3C', '#F39C12', '#27AE60', '#2E86C1', '#8E44AD']
OR_CAP = 100.0
sens_plot = sens_df.copy()
for col in ['or_value', 'or_lo', 'or_hi']:
    sens_plot[col] = sens_plot[col].clip(upper=OR_CAP)
for i, nk_thr in enumerate(nk_frac_thrs):
    ax = axes[i]
    sub = sens_plot[sens_plot['nk_frac_threshold'] == nk_thr].sort_values('clone_threshold')
    valid = sub['or_value'].notna()
    ax.errorbar(sub.loc[valid, 'clone_threshold'], sub.loc[valid, 'or_value'],
                yerr=[sub.loc[valid, 'or_value'] - sub.loc[valid, 'or_lo'],
                      sub.loc[valid, 'or_hi'] - sub.loc[valid, 'or_value']],
                fmt='o-', capsize=5, capthick=2, linewidth=2, markersize=8,
                color=colors[i % len(colors)], label=f'NK-frac={nk_thr}')
    ax.axhline(1, color='gray', ls='--', lw=1, alpha=0.6)
    ax.set_xscale('log')
    ax.set_xlabel('Clone cell-number threshold', fontsize=11)
    if i == 0:
        ax.set_ylabel(f'Odds Ratio (clipped at {OR_CAP})', fontsize=11)
    ax.set_title(f'NK-frac threshold = {nk_thr}', fontsize=12, fontweight='bold')
    ax.grid(alpha=0.3, ls=':')
    ax.legend(loc='upper right', fontsize=9)
plt.suptitle('Threshold Sensitivity: OR vs Clone Threshold (colored by NK-frac)',
             fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(os.path.join(RESULT, 'fig2_threshold_curve.png'), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(RESULT, 'fig2_threshold_curve.pdf'), bbox_inches='tight')
plt.close()
print('Threshold curve saved to result/fig2_threshold_curve.png', flush=True)

del adata_boot

print('=== DONE Fig2 ===', flush=True)
