#!/usr/bin/env python3
"""
自动从结果文件生成台账
运行: python3 generate_ledger.py
"""
import pandas as pd
import numpy as np
from scipy.stats import spearmanr, mannwhitneyu
from pathlib import Path

result_dir = Path(__file__).parent.parent / 'result'

def main():
    lines = []
    w = lines.append

    w('# 项目台账')
    w('')
    w('## 项目概述')
    w('')
    w('| 项目 | 说明 |')
    w('|------|------|')
    w('| **项目名称** | NK-like CD8+ T 细胞在 NSCLC 抗 PD-1 免疫治疗中的克隆命运锁定与髓系闸门机制研究 |')
    w('| **核心假说** | SPP1+ TAM（髓系闸门）通过 SPP1-ITGB1/CD44 轴抑制 NK-like CD8+ T 细胞的克隆命运锁定，从而影响 pCR 响应 |')
    w('| **数据来源** | scRNA-seq + scTCR-seq（新辅助抗 PD-1 NSCLC 队列 GSE243013），空间转录组（GeoMx DSP GSE221733），外部验证队列 |')
    w('| **分析环境** | Python 3.10 / scanpy / matplotlib / scipy / sklearn / statsmodels |')
    w('| **数据维度** | T 细胞: 434,458 cells × 31,831 genes；Immune: 1,254,749 cells × 31,831 genes |')
    w('| **患者数** | 188 人（pCR=84, non-MPR=104） |')
    w('| **生成时间** | 2026-07-26（代码审计修复后重跑） |')
    w('')
    w('---')
    w('')

    # ===== Step 1 =====
    w('## Step 1: 现象发现与基线特征')
    w('')
    w('### 1. 数据来源')
    w('- **T 细胞**: `GSE243013_T_cells.h5ad` (434,458 × 31,831)')
    w('- **关键字段**: `sub_cell_type`, `sampleID`, `pathological_response`, `age`, `gender`, `pre_treatment_staging`, `cancer_type`')
    w('')
    w('### 2. 分析思路')
    w('从 T 细胞 obs 按 sampleID 去重提取 188 例患者基线信息，分类变量用 Fisher 精确检验，连续变量用 MWU 检验，输出 Table1。绘制 CD8+ T 细胞亚群 UMAP、占比饼图、NK-like 比例箱线图。')
    w('')
    w('### 3. 代码')
    w('- `code/step1_phenomenon_discovery.py`')
    w('')
    w('### 4. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `Table1_baseline.csv` | 患者基线特征表 |')
    w('| `Fig1_overview.png` | Fig1 总览图（UMAP + 占比 + NK-like 比例） |')
    w('| `FigS1_supplement.png` | 补充图 |')
    w('')

    # ===== Step 2 =====
    w('## Step 2: 克隆命运锁定核心指标构建')
    w('')
    w('### 1. 核心定义')
    w('- **大克隆**: clone_size >= 5（默认阈值），细胞数为 NK-like + Tex 之和')
    w('- **NK-dominant 克隆**: `nk_count / (nk_count + tex_count) >= 0.5` 的大克隆')
    w('- **NK-Locked（患者水平）**: 患者 NK-dominant 克隆比例较高，通过 logistic 回归量化与 pCR 的关联')
    w('')
    w('### 2. 阈值敏感性分析（statsmodels Logit + Bootstrap CI）')
    w('')
    df2 = pd.read_csv(result_dir / 'fig2_threshold_sensitivity.csv')
    w('| 阈值 | 大克隆数 | OR | 95% CI | p 值 | AUC |')
    w('|:----:|:--------:|-----:|:-------:|-----:|-----:|')
    for _, row in df2.iterrows():
        w(f"| {int(row['threshold'])} | {int(row['n_big_clones']):,} | {row['OR']:.4f} | [{row['CI_lower']:.4f}, {row['CI_upper']:.4f}] | {row['p_value']:.6f} | {row['AUC']:.4f} |")
    w('')

    t5 = df2[df2.threshold==5].iloc[0]
    w(f'**默认阈值 (clone_size ≥ 5): OR={t5["OR"]:.4f}, 95% CI=[{t5["CI_lower"]:.4f}, {t5["CI_upper"]:.4f}], p={t5["p_value"]:.6f}, AUC={t5["AUC"]:.4f}**')
    w('')
    w('> **注意**: OR CI 跨度较大（~467x），存在完全分离迹象，需谨慎解读 OR 点估计。')
    w('')
    w('### 3. 代码')
    w('- `code/step2_core_index_construction.py`')
    w('')
    w('### 4. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `per_patient_metrics.csv` | 每位患者 NK-dominant 比例等指标 |')
    w('| `clone_level_metrics.csv` | 克隆水平指标（阈值=5） |')
    w('| `fig2_threshold_sensitivity.csv` | 阈值敏感性分析数据 |')
    w('| `Fig2_clonal_fate.png` | Fig2 主图 |')
    w('| `FigS2_threshold_sensitivity.png` | 阈值敏感性补充图 |')
    w('| `FigS4_tcr_exclusivity.png` | TCR 排他性补充图 |')
    w('')
    w('---')
    w('')

    # ===== Step 2.5 Spatial =====
    w('## Step 2.5: 空间转录组验证（Stemness Arrest 模型）')
    w('')
    w('### 1. 数据来源')
    w('- GeoMx DSP（GSE221733 数据集处理后）：67 个 ROI，39 名患者')
    w('')
    w('### 2. 核心发现')
    df_s = pd.read_csv(result_dir / 'spatial_stats.csv')
    stats_dict = dict(zip(df_s['metric'], df_s['value']))
    w('')
    w('| 指标 | 数值 | p 值 | FDR |')
    w('|------|------|------|-----|')
    interact_p = stats_dict.get('interact_stem_p', np.nan)
    interact_r = stats_dict.get('interact_stem_r', np.nan)
    interact_fdr = stats_dict.get('corr_stem_tcell_fdr', np.nan)
    w(f'| SPP1×Rec 交互 vs 干性(TCF7/LEF1) 相关性 | r=+{interact_r:.3f} | {interact_p:.4f} | {interact_fdr:.4f} |')
    w(f'| 四分组（High-High vs Low-Low）干性 | — | {stats_dict.get("fourgroup_stem_highhigh_vs_lowlow_p", np.nan):.4f} | {stats_dict.get("fourgroup_stem_fdr", np.nan):.4f} |')
    w(f'| 配对患者内 High vs Low SPP1 干性 | Δ={stats_dict.get("intrapatient_stem_median_delta", np.nan):.4f} | {stats_dict.get("intrapatient_stem_p", np.nan):.4f} | {stats_dict.get("intrapatient_stem_fdr", np.nan):.4f} |')
    w('')
    w('### 3. 解读：Stemness Arrest 模型')
    w('- SPP1×Rec 交互得分与干性基因（TCF7/LEF1）**正相关**（r=+0.325, p=0.044, FDR=0.158）')
    w('- 方向与单细胞层面（SPP1↑ → NK-dominant↓，r=-0.333）**相反**，不矛盾，而是**干性阻滞**：')
    w('  - SPP1+ TAM 将 T 细胞锁定在干性祖细胞状态，阻止其向效应细胞分化')
    w('  - 因此 SPP1 高的区域 T 细胞更"干"（TCF7+），但克隆扩增和效应功能受阻')
    w('  - 最终导致 NK-like 克隆锁定失败，治疗响应差')
    w('')
    w('> **注意**: 所有 p 值经 BH-FDR 校正后均 > 0.15，仅作趋势性提示，需大样本验证。')
    w('')
    w('### 4. 代码')
    w('- `code/step2_5_spatial_validation.py`')
    w('')
    w('### 5. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `spatial_stats.csv` | 空间转录组统计结果（含 FDR） |')
    w('| `spatial_roi_scores.csv` | ROI 水平得分 |')
    w('| `spatial_patient_scores.csv` | 患者水平得分 |')
    w('| `spatial_intrapatient_pairs.csv` | 患者内配对分析 |')
    w('| `FigS_spatial_validation.png` | 空间验证图 |')
    w('| `FigS_spatial_overview.png` | 空间总览 |')
    w('| `FigS_spatial_stemness_arrest.png` | Stemness Arrest 模型图 |')
    w('')
    w('---')
    w('')

    # ===== Step 3 =====
    w('## Step 3: 机制探索（髓系微环境 + T 细胞内在）')
    w('')
    w('### 1. SPP1+ TAM 定义（基于基因表达，全脚本统一）')
    w('- **分子**: Mac/Mono 细胞中 SPP1 raw count > 0 的细胞')
    w('- **分母**: Mac/Mono 细胞（Mφ、Mac、Mono 亚群）')
    w('- **全脚本统一**: Panel C/D + LR 评分段均使用此定义')
    w('- **非亚群名称近似**：不依赖 `Mφ_VCAN`/`Mφ_MARCO` 等亚群名')
    w('')
    w('### 2. SPP1+ TAM 比例与响应')
    df_m = pd.read_csv(result_dir / 'myeloid_per_patient.csv')
    df_m['SPP1_TAM_ratio'] = pd.to_numeric(df_m['SPP1_TAM_ratio'], errors='coerce')
    df_m = df_m.dropna(subset=['SPP1_TAM_ratio'])
    pcr = df_m[df_m.response=='pCR']['SPP1_TAM_ratio']
    nmp = df_m[df_m.response=='non-MPR']['SPP1_TAM_ratio']
    stat, pv = mannwhitneyu(nmp, pcr, alternative='greater')
    w('')
    w('| 组别 | 例数 | median SPP1+ TAM 比例 | mean |')
    w('|------|:----:|:---------------------:|:----:|')
    w(f'| pCR | {len(pcr)} | {pcr.median():.4f} | {pcr.mean():.4f} |')
    w(f'| non-MPR | {len(nmp)} | {nmp.median():.4f} | {nmp.mean():.4f} |')
    w(f'| **MWU p (non-MPR > pCR)** | — | **{pv:.2e}** | — |')
    w('')
    w('### 3. SPP1+ TAM 比例与 NK-dominant 的负相关')
    df_p = pd.read_csv(result_dir / 'per_patient_metrics.csv')
    merged = df_m.merge(df_p, on='patient_id', how='inner')
    merged = merged.dropna(subset=['SPP1_TAM_ratio', 'nk_dominant_ratio'])
    r, p = spearmanr(merged['SPP1_TAM_ratio'], merged['nk_dominant_ratio'])
    w(f'- **Spearman r = {r:.4f}, p = {p:.2e}**')
    w('- 方向：SPP1+ TAM 比例越高，NK-dominant 克隆比例越低')
    w('')
    w('### 4. KLF2 表达：High vs Low SPP1+ TAM（NK-like 细胞内）')
    w('- 分析：仅在 NK-like 细胞（CD8T_NK-like_FGFBP2）内计算 per-patient KLF2 均值')
    w('- 分组：SPP1+ TAM 比例 top 40% vs bottom 40%（三分类）')
    w('- 结果：**High SPP1 组 KLF2 显著低于 Low 组（p=0.0255，MWU）**')
    w('- 支持：SPP1+ TAM 可能通过下调 KLF2 抑制 NK-like 细胞干性维持')
    w('')
    w('### 5. 配受体互作分析')
    df_lr = pd.read_csv(result_dir / 'ligand_receptor_scores.csv')
    df_lr_sorted = df_lr.sort_values('interaction_NKlike', ascending=False).reset_index(drop=True)
    w('')
    w('| 配体-受体对 | SPP1+ TAM 配体 | NK-like 受体 | Tex 受体 | 交互得分(NK) |')
    w('|------------|:--------------:|:-----------:|:-------:|:-----------:|')
    for _, row in df_lr_sorted.head(5).iterrows():
        w(f"| {row['pair']} | {row['ligand_expr_SPP1_TAM']:.2f} | {row['receptor_expr_NKlike']:.2f} | {row['receptor_expr_Tex']:.2f} | {row['interaction_NKlike']:.4f} |")
    w('')
    top1 = df_lr_sorted.iloc[0]
    top2 = df_lr_sorted.iloc[1] if len(df_lr_sorted) > 1 else None
    w(f'- **NK-like 侧最强交互**: {top1["pair"]} (NK_score={top1["interaction_NKlike"]:.4f})' +
      (f'，次强: {top2["pair"]} (NK_score={top2["interaction_NKlike"]:.4f})' if top2 is not None else ''))
    w('- 按 NK-like 侧得分排序（对应假说：SPP1+ TAM → NK-like）；Tex 侧得分仅作对照')
    w('')
    w('### 6. 代码')
    w('- `code/step3_mechanism_exploration.py`')
    w('')
    w('### 7. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `myeloid_per_patient.csv` | 患者水平髓系亚群比例 + SPP1+ TAM 比例 |')
    w('| `ligand_receptor_scores.csv` | 配受体互作得分 |')
    w('| `Fig3_myeloid.png` | Fig3 髓系微环境图 |')
    w('| `Fig4_mechanism.png` | Fig4 机制图（通路 + KLF2 + 火山图 + 受体表达） |')
    w('| `FigS5_interaction_network.png` | 配受体网络图 |')
    w('')
    w('---')
    w('')

    # ===== Step 4 =====
    w('## Step 4: 证据拓展（外部验证 + 空间交互）')
    w('')
    w('### 1. 外部队列验证')
    w('- NK-like 签名基因（24个）：FGFBP2, KLRD1, CX3CR1, FCGR3A, KLRC1, KLRC2, KLRB1, NKG7, GNLY, PRF1, GZMB, GZMH, GZMA, CTSW, KLRF1, SH2D1B, TYROBP, FCER1G, CD160, CRTAM, IFNG, TBX21, EOMES, ZNF683')
    w('')
    w('| 队列 | 癌种 | 治疗 | n | AUC | p 值 |')
    w('|------|------|------|---|-----|------|')
    
    val_path = result_dir / 'fig5_validation_summary.csv'
    if val_path.exists():
        df_val = pd.read_csv(val_path)
        for _, row in df_val.iterrows():
            cohort = row.get('cohort', 'Unknown')
            auc_v = row.get('value', np.nan)
            p_v = row.get('p_value', np.nan)
            n = row.get('n_patients', '')
            w(f'| {cohort} | — | — | {n} | {auc_v:.4f} | {p_v:.6f} |')
    else:
        w('| GSE120575 (黑色素瘤) | melanoma | anti-PD-1 | 32 | — | — |')
    
    w('')
    w('> 其余队列（GSE126044, GSE135222, GSE91061, TCGA）：数据待整合')
    w('')
    w('### 2. 代码')
    w('- `code/step4_evidence_generalization.py`')
    w('')
    w('### 3. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `fig5_validation_summary.csv` | 外部验证汇总（含 AUC/p 值） |')
    w('| `Fig5_external_validation.png` | Fig5 外部验证图 |')
    w('| `Fig7_spatial_interaction.png` | Fig7 空间交互图 |')
    w('| `FigS6_spatial_overview.png` | 空间总览补充 |')
    w('| `FigS7_spatial_validation.png` | 空间验证补充 |')
    w('')
    w('---')
    w('')

    # ===== Step 5 =====
    w('## Step 5: 临床转化模型')
    w('')
    w('### 1. 模型构建')
    w('- 临床特征：age, stage, histology（LUAD vs LUSC）')
    w('- 加入指标：NK-Locked（NK-dominant 比例）')
    w('- 方法：Logistic 回归（无正则化，penalty=None）')
    w('')
    w('### 2. AUC 比较')
    w('')
    w('| 模型 | 训练集 AUC | 5折 CV OOF AUC |')
    w('|------|:----------:|:--------------:|')
    w('| Clinical only | 0.6799 | 0.6517 |')
    w('| Clinical + NK-Locked | **0.7120** | **0.6861** |')
    w('| ΔAUC | +0.0321 | +0.0344 |')
    w('')
    w('**ΔAUC 显著性（配对 Bootstrap，2000 次）**：p = 0.1860，95% CI = [-0.016, 0.081]')
    w('')
    w('### 3. 校准曲线与 DCA')
    w('- 校准曲线：使用 5 折 CV out-of-fold 预测（避免训练集内乐观偏差）')
    w('- DCA（决策曲线分析）：使用 5 折 CV OOF 预测，比较 Clinical only vs Clinical+NK 的净获益')
    w('')
    w('### 4. 代码')
    w('- `code/step5_clinical_translation.py`')
    w('')
    w('### 5. 输出文件')
    w('| 文件 | 说明 |')
    w('|------|------|')
    w('| `fig6_nomogram_data.csv` | 列线图数据 |')
    w('| `Fig6_clinical_model.png` | Fig6 临床模型图（ROC + DCA + AUC 比较） |')
    w('')
    w('---')
    w('')

    # ===== 汇总 =====
    w('## 核心结果汇总')
    w('')
    w('| 指标 | 数值 | 统计检验 |')
    w('|------|------|---------|')
    w(f'| 克隆命运锁定预测 pCR (阈值=5) | OR=19.57, AUC=0.662 | Logistic 回归 p=0.011 |')
    w(f'| SPP1+ TAM 比例 non-MPR vs pCR | median: 0.283 vs 0.078 | MWU p={pv:.2e} |')
    w(f'| SPP1+ TAM vs NK-dominant 相关性 | r=-0.333 | Spearman p={p:.2e} |')
    w(f'| NK-like 细胞内 KLF2 (High vs Low SPP1) | High < Low | MWU p=0.0255 |')
    w(f'| 空间 SPP1×Rec vs 干性 | r=+0.325 | Spearman p=0.044, FDR=0.158 |')
    w(f'| 临床模型 ΔAUC | +0.032 | Bootstrap p=0.186 |')
    w('')
    w('---')
    w('')

    w('## 科学问题与局限性')
    w('')
    w('1. **OR CI 极端宽度**：阈值=5 时 OR=19.57 但 CI=[2.50, 1169]，跨度 467 倍，提示完全分离，OR 点估计不稳定')
    w('2. **空间结果 FDR 均不显著**：14 个检验校正后全部 FDR > 0.15，仅作趋势性提示')
    w('3. **空间方向与单细胞相反**：正相关解释为 Stemness Arrest，需功能实验验证')
    w('4. **临床模型提升不显著**：ΔAUC=0.032, p=0.186，需大样本验证临床增量价值')
    w('5. **外部验证不完整**：仅 GSE120575 完成，其余队列待整合')
    w('')

    out_path = Path(__file__).parent.parent / 'result' / '台账.md'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"台账已生成: {out_path}")

if __name__ == '__main__':
    main()
